### ISSUE TITLE
React to Element Template bindings

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js-json-data-provider#2]
### What should we do?

When an Element Template is applied, still show the data section, unless the element template binds to the property itself

### Why should we do it?

So example data seamlessly integrates into the connectors story

**Comment by smbea** [comment]
Shouldn't https://github.com/bpmn-io/bpmn-js-json-data-provider/pull/5 have closed this?

**Comment by marstamm** [comment]
#5 depended on https://github.com/bpmn-io/bpmn-js-json-data-provider/pull/4, so it had a different base branch. We should not close it until it is merged to `main`

**Comment by smbea** [comment]
Go it, pls ignore

**Comment by marstamm** [comment]
Added `closes` tag to #4, thanks for bringing it up
